# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Full Release of Extension

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  package:
    name: Package
    uses: ./.github/workflows/package.yaml

  release:
    name: Publish VSCode Extension to Marketplace & Create GitHub Release
    runs-on: ubuntu-latest
    needs: package
    if: success() && startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Grab artifacts (vsix files)
      uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4

    - name: Create list of vsix files
      id: set-list
      run: |
        FILES=$(find . -name "*.vsix" -exec basename {} \; | paste -sd "," -)
        echo "files=$FILES" >> "${GITHUB_OUTPUT}"

    - name: Publish to GitHub Releases
      uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2
      if: success() && startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ steps.set-list.outputs.files }}
        generate_release_notes: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to VS Code Marketplace
      run: npx vsce publish --packagePath $(find . -iname '*.vsix')
      if: success() && startsWith(github.ref, 'refs/tags/')
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
